/* ==========================================================================
   Which photographs exist in /images
   --------------------------------------------------------------------------
   Updated dynamically with all active photographs.
   ========================================================================== */
window.UC_IMAGES = [
  "pages/bio.jpg",
  "pages/conspanel.jpg",
  "pages/cta.jpg",
  "pages/faisal-mosque.jpg",
  "pages/hanimal-skin-texture.jpg",
  "pages/haxminster-designs.jpg",
  "pages/hdyed.jpg",
  "pages/hdyed-rugs.jpg",
  "pages/hero.jpg",
  "pages/hhand-knotted.jpg",
  "pages/hluxurious-plains.jpg",
  "pages/hnatural-designs.jpg",
  "pages/hnatural-stripes.jpg",
  "pages/hnoble-natural.jpg",
  "pages/homedyed.jpg",
  "pages/homenoble-natural.jpg",
  "pages/homerugs.jpg",
  "pages/homespiritual-mosque.jpg",
  "pages/homewooden-flooring.jpg",
  "pages/pspiritual-mosque.jpg",
  "pages/sucycle.jpg",
  "pages/warpanel.jpg",
  "partners/askari-bank.webp",
  "partners/bahria-grand.png",
  "partners/belmorris.png",
  "partners/fatima-group.png",
  "partners/ifq-hotel.png",
  "partners/mughal-e-azam.png",
  "partners/nishat-hotel.png",
  "partners/noble-natural.png",
  "partners/qasar-e-noor.png",
  "partners/regalia-hotel.png",
  "partners/royal-orchard.webp",
  "partners/trusted-partners.png",
  "partners/zafar-group.png",
  "products/banquet-medallion.jpg",
  "products/blackout-curtain.jpg",
  "products/corridor-axminster.jpg",
  "products/madina-green.jpg",
  "products/mughal-garden.jpg"
];

/* Duplicate photographs removed from disk — alias each to the kept copy. */
window.UC_IMG_ALIAS = {
  "pages/about1.jpg": "pages/conspanel.jpg",
  "pages/abouthead.jpg": "pages/hero.jpg",
  "pages/aboutp.jpg": "pages/homedyed.jpg",
  "pages/aboutshop.jpg": "pages/hero.jpg",
  "pages/carehead.jpg": "pages/homerugs.jpg",
  "pages/conshead.jpg": "pages/cta.jpg",
  "pages/conthead.jpg": "pages/hero.jpg",
  "pages/faqhead.jpg": "pages/homerugs.jpg",
  "pages/hcontemporary-stripes.jpg": "pages/homedyed.jpg",
  "pages/hcurtains.jpg": "pages/cta.jpg",
  "pages/hexclusive-animal-skin-texture.jpg": "pages/hanimal-skin-texture.jpg",
  "pages/hhand-carved.jpg": "pages/homerugs.jpg",
  "pages/hhospitality.jpg": "pages/hero.jpg",
  "pages/hmosques.jpg": "pages/faisal-mosque.jpg",
  "pages/hnatural-plains.jpg": "pages/homenoble-natural.jpg",
  "pages/hnatural-rugs.jpg": "pages/homenoble-natural.jpg",
  "pages/homecurtains.jpg": "pages/cta.jpg",
  "pages/hothers.jpg": "pages/cta.jpg",
  "pages/hrugs.jpg": "pages/homerugs.jpg",
  "pages/hspiritual-mosque.jpg": "pages/faisal-mosque.jpg",
  "pages/hwooden-flooring.jpg": "pages/homewooden-flooring.jpg",
  "pages/national-assembly.jpg": "pages/cta.jpg",
  "pages/panimal-skin-texture.jpg": "pages/hanimal-skin-texture.jpg",
  "pages/paxminster-designs.jpg": "pages/haxminster-designs.jpg",
  "pages/pcontemporary-stripes.jpg": "pages/homedyed.jpg",
  "pages/pcurtains.jpg": "pages/cta.jpg",
  "pages/pdyed.jpg": "pages/hdyed.jpg",
  "pages/pdyed-rugs.jpg": "pages/hdyed-rugs.jpg",
  "pages/pexclusive-animal-skin-texture.jpg": "pages/hanimal-skin-texture.jpg",
  "pages/phand-carved.jpg": "pages/homerugs.jpg",
  "pages/phand-knotted.jpg": "pages/hhand-knotted.jpg",
  "pages/phospitality.jpg": "products/banquet-medallion.jpg",
  "pages/pjhead.jpg": "pages/cta.jpg",
  "pages/pjside.jpg": "pages/conspanel.jpg",
  "pages/pluxurious-plains.jpg": "pages/hluxurious-plains.jpg",
  "pages/pmosques.jpg": "pages/homespiritual-mosque.jpg",
  "pages/pnatural-designs.jpg": "pages/hnatural-designs.jpg",
  "pages/pnatural-plains.jpg": "pages/homenoble-natural.jpg",
  "pages/pnatural-rugs.jpg": "pages/hnoble-natural.jpg",
  "pages/pnatural-stripes.jpg": "pages/hnatural-stripes.jpg",
  "pages/pnoble-natural.jpg": "pages/hnoble-natural.jpg",
  "pages/pothers.jpg": "products/mughal-garden.jpg",
  "pages/prodhead.jpg": "pages/hero.jpg",
  "pages/prugs.jpg": "pages/homerugs.jpg",
  "pages/pthospitality.jpg": "pages/hero.jpg",
  "pages/ptmosques.jpg": "pages/faisal-mosque.jpg",
  "pages/ptothers.jpg": "pages/cta.jpg",
  "pages/pwooden-flooring.jpg": "pages/homewooden-flooring.jpg",
  "pages/sunat.jpg": "pages/sucycle.jpg",
  "pages/sushead.jpg": "pages/sucycle.jpg",
  "pages/tanimal-skin-texture.jpg": "pages/hanimal-skin-texture.jpg",
  "pages/taxminster-designs.jpg": "pages/haxminster-designs.jpg",
  "pages/tcontemporary-stripes.jpg": "pages/homedyed.jpg",
  "pages/tdyed-rugs.jpg": "pages/homedyed.jpg",
  "pages/texclusive-animal-skin-texture.jpg": "pages/hanimal-skin-texture.jpg",
  "pages/thand-carved.jpg": "pages/homerugs.jpg",
  "pages/thand-knotted.jpg": "pages/hhand-knotted.jpg",
  "pages/tluxurious-plains.jpg": "pages/hluxurious-plains.jpg",
  "pages/tnatural-designs.jpg": "pages/hnatural-designs.jpg",
  "pages/tnatural-plains.jpg": "pages/homenoble-natural.jpg",
  "pages/tnatural-rugs.jpg": "pages/homenoble-natural.jpg",
  "pages/tnatural-stripes.jpg": "pages/hnatural-stripes.jpg",
  "pages/warhead.jpg": "pages/bio.jpg",
  "pages/wool.jpg": "pages/homenoble-natural.jpg",
  "pages/woolhead.jpg": "pages/bio.jpg",
  "pages/woolpanel.jpg": "pages/homenoble-natural.jpg",
  "products/block-stripe.jpg": "pages/hnatural-stripes.jpg",
  "products/bordered-plain.jpg": "pages/hdyed-rugs.jpg",
  "products/carved-border.jpg": "pages/homerugs.jpg",
  "products/carved-floral.jpg": "pages/homerugs.jpg",
  "products/carved-medallion.jpg": "pages/homerugs.jpg",
  "products/charcoal-fleece.jpg": "products/blackout-curtain.jpg",
  "products/custom-mosque.jpg": "pages/faisal-mosque.jpg",
  "products/engineered-wood.jpg": "pages/homewooden-flooring.jpg",
  "products/fleece-stripe.jpg": "pages/hnatural-stripes.jpg",
  "products/fortress-plain.jpg": "pages/homenoble-natural.jpg",
  "products/heather-loop.jpg": "pages/homenoble-natural.jpg",
  "products/herati-allover.jpg": "pages/hhand-knotted.jpg",
  "products/herringbone-parquet.jpg": "pages/homewooden-flooring.jpg",
  "products/herring-stripe.jpg": "pages/hnatural-stripes.jpg",
  "products/hide-look-rug.jpg": "pages/hanimal-skin-texture.jpg",
  "products/jamaat-runner.jpg": "products/madina-green.jpg",
  "products/jute-weave.jpg": "pages/hnatural-designs.jpg",
  "products/laminate-oak.jpg": "pages/homewooden-flooring.jpg",
  "products/leopard-texture.jpg": "pages/hanimal-skin-texture.jpg",
  "products/loop-plain.jpg": "products/blackout-curtain.jpg",
  "products/mehrab-arch.jpg": "pages/pspiritual-mosque.jpg",
  "products/modern-abstract.jpg": "pages/homedyed.jpg",
  "products/musalla-rows.jpg": "pages/conspanel.jpg",
  "products/natural-basketweave.jpg": "pages/hnatural-designs.jpg",
  "products/natural-chevron.jpg": "pages/hnoble-natural.jpg",
  "products/natural-diamond.jpg": "pages/hnatural-designs.jpg",
  "products/oatmeal-berber.jpg": "pages/homenoble-natural.jpg",
  "products/ocelot-rug.jpg": "pages/hanimal-skin-texture.jpg",
  "products/ombre-rug.jpg": "pages/homewooden-flooring.jpg",
  "products/ombre-stripe.jpg": "pages/homedyed.jpg",
  "products/persian-medallion.jpg": "pages/hhand-knotted.jpg",
  "products/pin-stripe.jpg": "pages/hnatural-stripes.jpg",
  "products/python-texture.jpg": "pages/hanimal-skin-texture.jpg",
  "products/roller-blind.jpg": "products/blackout-curtain.jpg",
  "products/roman-blind.jpg": "pages/hnatural-stripes.jpg",
  "products/royale-axminster.jpg": "pages/hero.jpg",
  "products/saddar-stripe.jpg": "pages/homedyed.jpg",
  "products/saxony-deep.jpg": "pages/hluxurious-plains.jpg",
  "products/sheer-net.jpg": "products/blackout-curtain.jpg",
  "products/silk-blend-knotted.jpg": "pages/hhand-knotted.jpg",
  "products/sisal-boucle.jpg": "products/blackout-curtain.jpg",
  "products/skirting-accessories.jpg": "pages/homewooden-flooring.jpg",
  "products/snow-leopard-rug.jpg": "pages/hanimal-skin-texture.jpg",
  "products/spc-floor.jpg": "pages/homewooden-flooring.jpg",
  "products/stone-twist.jpg": "pages/homenoble-natural.jpg",
  "products/ticking-stripe.jpg": "pages/hnatural-stripes.jpg",
  "products/tribal-geometric.jpg": "pages/hnatural-designs.jpg",
  "products/twist-plain.jpg": "products/blackout-curtain.jpg",
  "products/undyed-wool-rug.jpg": "pages/hdyed-rugs.jpg",
  "products/velvet-drape.jpg": "pages/haxminster-designs.jpg",
  "products/velvet-touch.jpg": "pages/haxminster-designs.jpg",
  "products/vertical-blind.jpg": "pages/hnatural-stripes.jpg",
  "products/vinyl-floor.jpg": "pages/homewooden-flooring.jpg",
  "products/wooden-blind.jpg": "pages/homewooden-flooring.jpg",
  "products/zebra-blind.jpg": "pages/hnatural-stripes.jpg",
  "products/zebra-texture.jpg": "pages/hanimal-skin-texture.jpg"
};

