/* ==========================================================================
   Unique Carpet & Interior — product catalogue
   Generated file. Edit freely: every page reads from this one array.
   coll = collection slug, and also the page the product lives on.
   ========================================================================== */
(function (global) {
  "use strict";
  var PRODUCTS = [
    { id: "fortress-plain", name: "Fortress Plain", coll: "luxurious-plains", sub: "Dyed Plain", art: "plain", pal: "ivory",
      blurb: "A dense level-loop plain in warm ivory \u2014 the quiet backdrop we fit more of than anything else.",
      tags: ["Level loop", "Wool blend", "Any shade"] },
    { id: "velvet-touch", name: "Velvet Touch Plain", coll: "luxurious-plains", sub: "Dyed Plain", art: "plain", pal: "beige",
      blurb: "Cut-pile velvet finish with a soft sheen that shifts as you cross the room.",
      tags: ["Velvet finish", "Cut pile", "Formal rooms"] },
    { id: "saxony-deep", name: "Saxony Deep Plain", coll: "luxurious-plains", sub: "Dyed Plain", art: "plain", pal: "rose",
      blurb: "A long, luxurious saxony pile for bedrooms \u2014 the one people take their shoes off for.",
      tags: ["Saxony", "Deep pile", "Bedrooms"] },
    { id: "twist-plain", name: "Hard Twist Plain", coll: "luxurious-plains", sub: "Dyed Plain", art: "plain", pal: "grey",
      blurb: "Tightly twisted yarn that resists flattening, for stairs, halls and anywhere with real traffic.",
      tags: ["Hard twist", "Traffic areas", "Stairs"] },
    { id: "loop-plain", name: "Fine Loop Plain", coll: "luxurious-plains", sub: "Dyed Plain", art: "plain", pal: "charcoal",
      blurb: "A low, fine loop that takes castor wheels and office chairs without crushing.",
      tags: ["Fine loop", "Commercial", "Chair-friendly"] },
    { id: "saddar-stripe", name: "Saddar Irregular Stripe", coll: "contemporary-stripes", sub: "Stripe", art: "stripe", pal: "charcoal",
      blurb: "Irregular charcoal stripes that hide traffic marks \u2014 our most-specified office carpet.",
      tags: ["Irregular", "Office", "Traffic hiding"] },
    { id: "ombre-stripe", name: "Ombr\u00e9 Stripe", coll: "contemporary-stripes", sub: "Stripe", art: "stripe", pal: "teal",
      blurb: "Colour graded from deep to pale across the width, so the floor lightens as it meets the window.",
      tags: ["Ombr\u00e9", "Graded colour", "Wide rooms"] },
    { id: "pin-stripe", name: "Fine Pinstripe", coll: "contemporary-stripes", sub: "Stripe", art: "stripe", pal: "navy",
      blurb: "Narrow stripes at close intervals \u2014 reads almost as a texture until you stand on it.",
      tags: ["Pinstripe", "Subtle", "Corridors"] },
    { id: "block-stripe", name: "Wide Block Stripe", coll: "contemporary-stripes", sub: "Stripe", art: "stripe", pal: "maroon",
      blurb: "Broad bands of two or three colours for halls and long corridors that need the length broken up.",
      tags: ["Wide block", "Two or three colours", "Corridors"] },
    { id: "royale-axminster", name: "Royale Axminster", coll: "axminster-designs", sub: "Axminster", art: "axminster", pal: "crimson",
      blurb: "Classic florals in crimson and gold for banquet halls, marquees and hotel corridors.",
      tags: ["Axminster", "Hospitality", "Up to 12 colours"] },
    { id: "mughal-garden", name: "Mughal Garden Axminster", coll: "axminster-designs", sub: "Axminster", art: "axminster", pal: "emerald",
      blurb: "An all-over garden repeat in emerald and gold, drawn from Mughal garden planting patterns.",
      tags: ["All-over repeat", "Emerald", "Custom colourway"] },
    { id: "corridor-axminster", name: "Corridor Axminster", coll: "axminster-designs", sub: "Axminster", art: "axminster", pal: "navy",
      blurb: "A small-scale repeat designed to run continuously down a corridor without an obvious pattern drop.",
      tags: ["Small repeat", "Hotel corridor", "Seamless run"] },
    { id: "banquet-medallion", name: "Banquet Medallion", coll: "axminster-designs", sub: "Axminster", art: "medallion", pal: "maroon",
      blurb: "A centred medallion layout set out to your hall dimensions, with matching border and mitred corners.",
      tags: ["Centred medallion", "Made to hall size", "Mitred border"] },
    { id: "oatmeal-berber", name: "Oatmeal Berber", coll: "natural-plains", sub: "Natural Plain", art: "natural", pal: "linen",
      blurb: "Undyed fleece in its natural oatmeal, looped into a classic berber.",
      tags: ["Undyed", "Berber", "Bio-degradable"] },
    { id: "heather-loop", name: "Heather Loop", coll: "natural-plains", sub: "Natural Plain", art: "natural", pal: "ash",
      blurb: "Blended grey fleece with a flecked heather look that hides everything a house throws at it.",
      tags: ["Heather", "Flecked", "Family rooms"] },
    { id: "stone-twist", name: "Stone Natural Twist", coll: "natural-plains", sub: "Natural Plain", art: "natural", pal: "grey",
      blurb: "A hard-twist natural in mid stone, for halls and stairs that want no dye in them.",
      tags: ["Hard twist", "Undyed", "Stairs"] },
    { id: "charcoal-fleece", name: "Charcoal Fleece Plain", coll: "natural-plains", sub: "Natural Plain", art: "natural", pal: "charcoal",
      blurb: "The darkest fleece we can blend without dye \u2014 closer to slate than to black.",
      tags: ["Dark natural", "Undyed", "Contemporary"] },
    { id: "ticking-stripe", name: "Natural Ticking Stripe", coll: "natural-stripes", sub: "Natural Stripe", art: "stripe", pal: "linen",
      blurb: "Narrow two-tone stripe in undyed fleece, like mattress ticking under your feet.",
      tags: ["Two-tone", "Undyed", "Bedrooms"] },
    { id: "fleece-stripe", name: "Two-Tone Fleece Stripe", coll: "natural-stripes", sub: "Natural Stripe", art: "stripe", pal: "ash",
      blurb: "Oatmeal against stone in wide alternating bands \u2014 contrast without a dye bath.",
      tags: ["Wide band", "Undyed", "Living rooms"] },
    { id: "herring-stripe", name: "Herring Natural Stripe", coll: "natural-stripes", sub: "Natural Stripe", art: "stripe", pal: "sand",
      blurb: "Three natural tones stepped through the stripe so it shades gradually across the width.",
      tags: ["Three tones", "Graded", "Undyed"] },
    { id: "natural-diamond", name: "Natural Diamond", coll: "natural-designs", sub: "Natural Design", art: "jute", pal: "linen",
      blurb: "A diamond lattice formed by loop height alone \u2014 pattern you feel before you see it.",
      tags: ["Loop height", "Texture pattern", "Undyed"] },
    { id: "natural-basketweave", name: "Natural Basketweave", coll: "natural-designs", sub: "Natural Design", art: "jute", pal: "sand",
      blurb: "Over-and-under basket construction in undyed wool, with real depth to the surface.",
      tags: ["Basketweave", "Textured", "Hard-wearing"] },
    { id: "natural-chevron", name: "Natural Chevron", coll: "natural-designs", sub: "Natural Design", art: "herringbone", pal: "ash",
      blurb: "A soft chevron worked in cut-and-loop, reading as plain from across the room.",
      tags: ["Chevron", "Cut and loop", "Subtle"] },
    { id: "leopard-texture", name: "Leopard Texture", coll: "animal-skin-texture", sub: "Skin Texture", art: "hide", pal: "walnut",
      blurb: "Leopard markings drawn from the natural colour range of the fleece rather than printed on.",
      tags: ["Woven markings", "Natural tones", "Statement"] },
    { id: "zebra-texture", name: "Zebra Texture", coll: "animal-skin-texture", sub: "Skin Texture", art: "hide", pal: "ebony",
      blurb: "High-contrast banding in charcoal and cream, supplied as broadloom or a bound rug.",
      tags: ["High contrast", "Broadloom or rug", "Wool"] },
    { id: "python-texture", name: "Python Texture", coll: "animal-skin-texture", sub: "Skin Texture", art: "hide", pal: "sand",
      blurb: "A fine scale texture in sand and taupe \u2014 the quietest of the skin textures.",
      tags: ["Fine scale", "Neutral", "Understated"] },
    { id: "musalla-rows", name: "Musalla Prayer Rows", coll: "spiritual-mosque", sub: "Mosque Carpet", art: "mosque", pal: "emerald",
      blurb: "Woven saff lines that keep rows straight without floor tape. 120 cm row depth as standard.",
      tags: ["Saff rows", "120 cm depth", "Wall to wall"] },
    { id: "mehrab-arch", name: "Mehrab Arch Carpet", coll: "spiritual-mosque", sub: "Mosque Carpet", art: "mosque", pal: "teal",
      blurb: "An individual mehrab arch for each worshipper, in teal with an ivory outline.",
      tags: ["Mehrab", "Prayer hall", "Anti-slip"] },
    { id: "madina-green", name: "Madina Green Prayer Carpet", coll: "spiritual-mosque", sub: "Mosque Carpet", art: "mosque", pal: "olive",
      blurb: "The familiar deep green with a gold border, heat-sealed on site with no visible joins.",
      tags: ["Classic green", "Sealed seams", "Roll goods"] },
    { id: "jamaat-runner", name: "Jamaat Khana Runner", coll: "spiritual-mosque", sub: "Mosque Carpet", art: "stripe", pal: "emerald",
      blurb: "Bound runners for smaller prayer rooms and overflow areas, cut to the width of the space.",
      tags: ["Runner", "Bound edge", "Small rooms"] },
    { id: "custom-mosque", name: "Custom Mosque Programme", coll: "spiritual-mosque", sub: "Bespoke", art: "damask", pal: "gold",
      blurb: "Colour, motif and row width drawn to your hall plan, with a woven sample sent for approval first.",
      tags: ["Bespoke", "Sample approval", "Any size"] },
    { id: "carved-medallion", name: "Carved Medallion Rug", coll: "hand-carved", sub: "Hand Carved", art: "damask", pal: "beige",
      blurb: "A central medallion with every outline hand-sheared, so the motif casts its own shadow.",
      tags: ["Hand sheared", "Medallion", "Tone on tone"] },
    { id: "carved-border", name: "Carved Border Rug", coll: "hand-carved", sub: "Hand Carved", art: "damask", pal: "rose",
      blurb: "A plain field with a deeply carved border \u2014 the simplest carved rug and the easiest to live with.",
      tags: ["Carved border", "Plain field", "Any size"] },
    { id: "carved-floral", name: "Carved Floral Rug", coll: "hand-carved", sub: "Hand Carved", art: "damask", pal: "emerald",
      blurb: "An all-over floral, carved throughout, in a single colour family.",
      tags: ["All-over floral", "Single colour", "Wool blend"] },
    { id: "persian-medallion", name: "Persian Medallion Rug", coll: "hand-knotted", sub: "Hand Knotted", art: "medallion", pal: "crimson",
      blurb: "Knotted on a cotton warp with a central medallion, spandrels and a three-band border.",
      tags: ["Hand knotted", "Cotton warp", "Heirloom"] },
    { id: "tribal-geometric", name: "Tribal Geometric Rug", coll: "hand-knotted", sub: "Hand Knotted", art: "geo", pal: "rust",
      blurb: "Angular village drawing in madder reds and indigos, knotted a little coarser and all the better for it.",
      tags: ["Tribal", "Geometric", "Wool pile"] },
    { id: "herati-allover", name: "All-Over Herati Rug", coll: "hand-knotted", sub: "Hand Knotted", art: "damask", pal: "navy",
      blurb: "The Herati repeat carried across the whole field, with no medallion to anchor it.",
      tags: ["All-over", "Herati", "Fine knot"] },
    { id: "silk-blend-knotted", name: "Silk-Blend Knotted Rug", coll: "hand-knotted", sub: "Hand Knotted", art: "medallion", pal: "plum",
      blurb: "Wool with a silk-blend highlight in the motif, so the pattern lifts as the light moves.",
      tags: ["Silk blend", "High knot count", "Fine drawing"] },
    { id: "modern-abstract", name: "Modern Abstract Rug", coll: "dyed-rugs", sub: "Dyed Rug", art: "geo", pal: "navy",
      blurb: "Blocks, arcs and triangles in navy and brass, cut and bound to any rectangle you need.",
      tags: ["Contemporary", "Made to size", "Bound edge"] },
    { id: "ombre-rug", name: "Ombr\u00e9 Area Rug", coll: "dyed-rugs", sub: "Dyed Rug", art: "stripe", pal: "teal",
      blurb: "Colour graded across the rug so it shifts from deep to pale end to end.",
      tags: ["Ombr\u00e9", "Graded", "Living rooms"] },
    { id: "bordered-plain", name: "Bordered Plain Rug", coll: "dyed-rugs", sub: "Dyed Rug", art: "plain", pal: "maroon",
      blurb: "A plain field with a contrast border cut and inlaid \u2014 the tidiest rug in the range.",
      tags: ["Inlaid border", "Plain field", "Any size"] },
    { id: "jute-weave", name: "Natural Jute Rug", coll: "natural-rugs", sub: "Natural Rug", art: "jute", pal: "sand",
      blurb: "Chunky hand-woven jute in its own colour. Hard-wearing, and it grounds a room without adding pattern.",
      tags: ["Jute", "Hand woven", "Natural"] },
    { id: "undyed-wool-rug", name: "Undyed Wool Rug", coll: "natural-rugs", sub: "Natural Rug", art: "natural", pal: "linen",
      blurb: "Flat-woven undyed fleece, reversible, and light enough to lift and shake out.",
      tags: ["Flat weave", "Reversible", "Undyed"] },
    { id: "sisal-boucle", name: "Sisal Boucl\u00e9 Rug", coll: "natural-rugs", sub: "Natural Rug", art: "jute", pal: "ash",
      blurb: "A tight sisal boucl\u00e9 that stands up to dining chairs better than any other natural fibre.",
      tags: ["Sisal", "Boucl\u00e9", "Dining rooms"] },
    { id: "hide-look-rug", name: "Hide-Look Rug", coll: "exclusive-animal-skin-texture", sub: "Exclusive Texture", art: "hide", pal: "walnut",
      blurb: "Shaped like a hide, woven like a rug \u2014 vacuum it, clean it and repair it like anything else.",
      tags: ["Shaped edge", "Woven", "Statement"] },
    { id: "snow-leopard-rug", name: "Snow Leopard Rug", coll: "exclusive-animal-skin-texture", sub: "Exclusive Texture", art: "hide", pal: "ash",
      blurb: "Pale grey and cream markings on a soft pile, for a room that is otherwise very quiet.",
      tags: ["Pale tones", "Soft pile", "Bound edge"] },
    { id: "ocelot-rug", name: "Ocelot Rug", coll: "exclusive-animal-skin-texture", sub: "Exclusive Texture", art: "hide", pal: "rust",
      blurb: "Small dense markings in rust and black \u2014 the loudest thing we make, and deliberately so.",
      tags: ["Dense marking", "Rust and black", "One per room"] },
    { id: "blackout-curtain", name: "Blackout Curtains", coll: "curtains", sub: "Curtains", art: "drape", pal: "navy",
      blurb: "Triple-weave blackout fabric with a thermal lining that keeps the summer heat off the glass.",
      tags: ["Blackout", "Thermal lined", "Bedroom"] },
    { id: "sheer-net", name: "Sheer & Net Curtains", coll: "curtains", sub: "Curtains", art: "drape", pal: "linen",
      blurb: "Fine voiles that soften daylight and give privacy without shutting the room in.",
      tags: ["Sheer", "Voile", "Layering"] },
    { id: "velvet-drape", name: "Velvet Drapes", coll: "curtains", sub: "Curtains", art: "drape", pal: "plum",
      blurb: "Heavy cotton velvet, pinch-pleated and weighted at the hem so it hangs straight from day one.",
      tags: ["Velvet", "Pinch pleat", "Formal"] },
    { id: "roller-blind", name: "Roller & Motorised Blinds", coll: "curtains", sub: "Blinds", art: "blind", pal: "ash",
      blurb: "Chain-operated or motorised rollers in sunscreen, dim-out and blackout fabrics, sized to the millimetre.",
      tags: ["Roller", "Motorised", "Made to measure"] },
    { id: "zebra-blind", name: "Zebra Blinds", coll: "curtains", sub: "Blinds", art: "blind", pal: "beige",
      blurb: "Alternating sheer and opaque bands \u2014 slide them over each other to dial the daylight up or down.",
      tags: ["Zebra", "Day & night", "Living room"] },
    { id: "wooden-blind", name: "Wooden Venetian Blinds", coll: "curtains", sub: "Blinds", art: "blind", pal: "oak",
      blurb: "50 mm basswood slats with cloth tapes, in natural, walnut and white finishes.",
      tags: ["Venetian", "Basswood", "Tilt control"] },
    { id: "vertical-blind", name: "Vertical Blinds", coll: "curtains", sub: "Blinds", art: "blind", pal: "grey",
      blurb: "89 mm and 127 mm vanes for wide office glazing \u2014 the practical answer to a long window wall.",
      tags: ["Vertical", "Office", "Wide spans"] },
    { id: "roman-blind", name: "Roman Blinds", coll: "curtains", sub: "Blinds", art: "drape", pal: "olive",
      blurb: "Soft folds that stack neatly at the head \u2014 a curtain's look in a blind's space.",
      tags: ["Roman", "Soft fold", "Lined"] },
    { id: "laminate-oak", name: "Laminate Wooden Flooring", coll: "wooden-flooring", sub: "Laminate", art: "wood", pal: "oak",
      blurb: "AC4 and AC5 click-lock laminate in oak, teak and walnut d\u00e9cors. Fitted over foam underlay in a day.",
      tags: ["Laminate", "Click lock", "AC4 / AC5"] },
    { id: "vinyl-floor", name: "Vinyl Flooring", coll: "wooden-flooring", sub: "Vinyl", art: "wood", pal: "ash",
      blurb: "Rolls and planks in wood and stone d\u00e9cors. Warm underfoot, water tolerant, easy on the budget.",
      tags: ["Vinyl", "Water tolerant", "Economy"] },
    { id: "spc-floor", name: "SPC Rigid Core Flooring", coll: "wooden-flooring", sub: "SPC", art: "wood", pal: "walnut",
      blurb: "Stone-composite core with a wear layer over it \u2014 stable, and the closest thing to waterproof wood.",
      tags: ["SPC", "Waterproof core", "Commercial"] },
    { id: "engineered-wood", name: "Engineered Hardwood", coll: "wooden-flooring", sub: "Engineered", art: "wood", pal: "ebony",
      blurb: "A real hardwood top layer on a plywood base, so it behaves in our climate as solid planks do not.",
      tags: ["Real wood", "Multi-ply", "Sandable"] },
    { id: "herringbone-parquet", name: "Herringbone Parquet", coll: "wooden-flooring", sub: "Parquet", art: "herringbone", pal: "walnut",
      blurb: "Short blocks set at 45\u00b0 in herringbone or chevron. Slow to lay, and always the first thing noticed.",
      tags: ["Herringbone", "Chevron", "Statement floor"] },
    { id: "skirting-accessories", name: "Skirting & Profiles", coll: "wooden-flooring", sub: "Accessories", art: "herringbone", pal: "oak",
      blurb: "Matching skirting, stair nosings, reducers and T-profiles so every edge is finished properly.",
      tags: ["Skirting", "Profiles", "Finishing"] },
  ];

  /* collection slug -> parent group slug, used by the group pages */
  var PARENT = {
    "luxurious-plains": "dyed",
    "contemporary-stripes": "dyed",
    "axminster-designs": "dyed",
    "natural-plains": "noble-natural",
    "natural-stripes": "noble-natural",
    "natural-designs": "noble-natural",
    "animal-skin-texture": "noble-natural",
    "hand-carved": "rugs",
    "hand-knotted": "rugs",
    "dyed-rugs": "rugs",
    "natural-rugs": "rugs",
    "exclusive-animal-skin-texture": "rugs",
    "dyed": "dyed",
    "noble-natural": "noble-natural",
    "spiritual-mosque": "spiritual-mosque",
    "rugs": "rugs",
    "curtains": "curtains",
    "wooden-flooring": "wooden-flooring"
};

  global.UC_PRODUCTS = PRODUCTS;
  global.UC_PARENT = PARENT;
})(window);
